create table public.candidates (
    id bigint generated by default as identity primary key,
    name text not null,
    tagline text,
    photo_url text,
    created_at timestamptz default now()
);

create table public.votes (
    id bigint generated by default as identity primary key,

    voter_id uuid not null
        references auth.users(id)
        on delete cascade,

    candidate_id bigint not null
        references public.candidates(id)
        on delete restrict,

    created_at timestamptz default now(),

    constraint one_vote_per_voter
        unique (voter_id)
);

create table public.election_settings (
    id bigint primary key default 1,

    election_name text not null
        default 'CR Election 2026',

    status text not null
        default 'LIVE',

    start_time timestamptz,
    end_time timestamptz,

    winner_id bigint
        references public.candidates(id)
);

alter table public.candidates enable row level security;
alter table public.votes enable row level security;
alter table public.election_settings enable row level security;


create policy "Candidates visible to logged users"
on public.candidates
for select
to authenticated
using (true);


create policy "Votes visible to logged users"
on public.votes
for select
to authenticated
using (true);


create policy "Users can submit own vote"
on public.votes
for insert
to authenticated
with check (
    auth.uid() = voter_id
);


create policy "Election settings visible"
on public.election_settings
for select
to authenticated
using (true);


insert into public.election_settings
(
    election_name,
    status
)
values
(
    'CR Election 2026',
    'LIVE'
);